version: '3'
services:
  zookeeper: # zookeeper는 카프카 클러스터를 관리하기 위한 서비스
    image: confluentinc/cp-zookeeper:7.3.10
    environment:
      ZOOKEEPER_CLIENT_PORT : 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.10
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID : 1
      KAFKA_ZOOKEEPER_CONNECT : zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS : PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

